import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const POSITION_MAP = {
  farLeft: 'chunky_far_left',
  left: 'left',
  center: 'center',
  right: 'right',
  farRight: 'chunky_far_right',
}

export function convertVisualNovelToRenpy({
  world,
  script,
  manifest,
  storyId = script.id,
}) {
  const imageNames = buildImageNames(manifest)
  const lines = [
    '# Generated by scripts/vn-renpy/convert.mjs. Edit the Chunky VN JSON source instead.',
    '',
    'define config.name = "Chunky Chinese - RenPy Prototype"',
    'define narrator = Character(None)',
    '',
    'transform chunky_far_left:',
    '    xalign 0.08',
    '    yalign 1.0',
    '',
    'transform chunky_far_right:',
    '    xalign 0.92',
    '    yalign 1.0',
    '',
    'init python:',
    '    import json',
    '',
    '    def chunky_event(name, payload=None):',
    '        if payload is None:',
    '            payload = {}',
    '        payload["type"] = name',
    `        payload["storyId"] = ${pythonString(storyId)}`,
    '        if renpy.emscripten:',
    '            renpy.emscripten.run_script(',
    '                "window.parent && window.parent.postMessage(" + json.dumps({"source": "chunky-renpy", "payload": payload}) + ", \'*\')"',
    '            )',
    '',
    '    def chunky_line(node_id, text):',
    '        chunky_event("lineChanged", {"nodeId": node_id, "text": text})',
    '',
    '    def chunky_choice(node_id, choice_id, text):',
    '        chunky_event("choiceSelected", {"nodeId": node_id, "choiceId": choice_id, "text": text})',
    '',
    '    def chunky_complete(node_id, quest_id, outcome_id):',
    '        chunky_event("questComplete", {"nodeId": node_id, "questId": quest_id, "outcomeId": outcome_id})',
    '',
  ]

  for (const [id, asset] of Object.entries(manifest.backgrounds ?? {})) {
    lines.push(`image ${imageNames.backgrounds[id]} = ${pythonString(assetPath(asset, 'backgrounds'))}`)
  }
  for (const [id, asset] of Object.entries(manifest.sprites ?? {})) {
    lines.push(`image ${imageNames.sprites[id]} = ${pythonString(assetPath(asset, 'characters'))}`)
  }
  for (const [id, asset] of Object.entries(manifest.cinematics ?? {})) {
    lines.push(`image ${imageNames.cinematics[id]} = ${pythonString(assetPath(asset, 'cinematics'))}`)
  }

  lines.push('', 'label start:', '    $ chunky_event("ready", {"initialNodeId": ' + pythonString(script.initialNodeId) + '})')
  lines.push(`    jump ${renpyLabel(script.initialNodeId)}`, '')

  for (const node of orderedNodes(script)) {
    lines.push(`label ${renpyLabel(node.id)}:`)
    emitNode(lines, node, script, world, imageNames)
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}

export function writeRenpyPrototype({
  rootDir,
  worldPath,
  outDir,
  storyId,
}) {
  const world = readJson(path.join(rootDir, 'public', worldPath))
  const scriptPath = firstQuestScriptPath(world, storyId)
  const script = readJson(path.join(rootDir, 'public', scriptPath))
  const manifest = readJson(path.join(rootDir, 'public', world.assetManifestPath))
  const projectDir = path.join(rootDir, outDir)
  const gameDir = path.join(projectDir, 'game')

  rmSync(gameDir, { recursive: true, force: true })
  mkdirSync(gameDir, { recursive: true })

  writeFileSync(
    path.join(gameDir, 'script.rpy'),
    convertVisualNovelToRenpy({ world, script, manifest, storyId: storyId ?? script.id }),
    'utf8',
  )
  writeFileSync(path.join(gameDir, 'options.rpy'), buildOptionsRpy(script), 'utf8')
  writeFileSync(path.join(projectDir, 'progressive_download.txt'), buildProgressiveDownload(), 'utf8')
  writeFileSync(path.join(projectDir, 'README.md'), buildReadme(script), 'utf8')
  copyAssets(rootDir, gameDir, manifest)

  return {
    projectDir,
    gameDir,
    scriptPath,
    nodeCount: Object.keys(script.nodes ?? {}).length,
    assetCount:
      Object.keys(manifest.backgrounds ?? {}).length +
      Object.keys(manifest.sprites ?? {}).length +
      Object.keys(manifest.cinematics ?? {}).length,
  }
}

function emitNode(lines, node, script, world, imageNames) {
  if (node.type === 'line') {
    emitScene(lines, node.scene, imageNames)
    const text = node.text?.chinese ?? ''
    const speaker = node.speaker ? speakerName(script, node.speaker) : undefined
    lines.push(`    $ chunky_line(${pythonString(node.id)}, ${pythonString(text)})`)
    lines.push(`    narrator ${pythonString(speaker ? `${speaker}: ${text}` : text)}`)
    emitNext(lines, node.nextId)
    return
  }

  if (node.type === 'choice') {
    const prompt = node.prompt?.chinese
    if (prompt) {
      lines.push(`    $ chunky_line(${pythonString(node.id)}, ${pythonString(prompt)})`)
      lines.push(`    narrator ${pythonString(prompt)}`)
    }
    lines.push('    menu:')
    for (const choice of node.choices ?? []) {
      const label = choice.label?.chinese ?? choice.id
      lines.push(`        ${pythonString(label)}:`)
      lines.push(`            $ chunky_choice(${pythonString(node.id)}, ${pythonString(choice.id)}, ${pythonString(label)})`)
      lines.push(`            jump ${renpyLabel(choice.nextId)}`)
    }
    return
  }

  if (node.type === 'cinematic') {
    const imageName = imageNames.cinematics[node.imageId]
    if (imageName) lines.push(`    scene ${imageName}`)
    const caption = node.caption?.chinese ?? node.description
    lines.push(`    $ chunky_line(${pythonString(node.id)}, ${pythonString(caption)})`)
    lines.push(`    narrator ${pythonString(caption)}`)
    emitNext(lines, node.nextId)
    return
  }

  if (node.type === 'questResult') {
    const summary = node.summary?.chinese
    if (summary) lines.push(`    narrator ${pythonString(summary)}`)
    lines.push(`    $ chunky_complete(${pythonString(node.id)}, ${pythonString(node.questId)}, ${pythonString(node.outcomeId)})`)
    lines.push('    return')
    return
  }

  if (node.type === 'end') {
    const summary = node.summary?.chinese
    if (summary) lines.push(`    narrator ${pythonString(summary)}`)
    lines.push('    return')
    return
  }

  if (node.type === 'cardBattle') {
    lines.push(`    $ chunky_event("cardBattle", {"nodeId": ${pythonString(node.id)}, "encounterId": ${pythonString(node.encounterId)}})`)
    lines.push(`    jump ${renpyLabel(node.winNextId)}`)
  }
}

function emitScene(lines, scene, imageNames) {
  if (!scene) return
  if (scene.backgroundId && imageNames.backgrounds[scene.backgroundId]) {
    lines.push(`    scene ${imageNames.backgrounds[scene.backgroundId]}`)
  }
  if (scene.clearCharacters) lines.push('    hide screen chunky_scene')
  for (const character of scene.characters ?? []) {
    const imageName = imageNames.sprites[character.spriteId]
    if (!imageName) continue
    const position = POSITION_MAP[character.position] ?? 'center'
    lines.push(`    show ${imageName} at ${position}`)
  }
}

function emitNext(lines, nextId) {
  if (nextId) lines.push(`    jump ${renpyLabel(nextId)}`)
  else lines.push('    return')
}

function orderedNodes(script) {
  const nodes = script.nodes ?? {}
  const order = []
  const seen = new Set()
  walk(script.initialNodeId)
  for (const id of Object.keys(nodes).sort()) walk(id)
  return order

  function walk(id) {
    if (!id || seen.has(id) || !nodes[id]) return
    seen.add(id)
    const node = nodes[id]
    order.push(node)
    for (const nextId of nextIds(node)) walk(nextId)
  }
}

function nextIds(node) {
  if (node.type === 'choice') return (node.choices ?? []).map((choice) => choice.nextId)
  if (node.type === 'cardBattle') return [node.winNextId, node.loseNextId].filter(Boolean)
  return node.nextId ? [node.nextId] : []
}

function buildImageNames(manifest) {
  return {
    backgrounds: Object.fromEntries(Object.keys(manifest.backgrounds ?? {}).map((id) => [id, `bg_${renpyName(id)}`])),
    sprites: Object.fromEntries(Object.keys(manifest.sprites ?? {}).map((id) => [id, `spr_${renpyName(id)}`])),
    cinematics: Object.fromEntries(Object.keys(manifest.cinematics ?? {}).map((id) => [id, `cg_${renpyName(id)}`])),
  }
}

function assetPath(asset, folder) {
  return `images/${folder}/${path.basename(asset.src)}`
}

function copyAssets(rootDir, gameDir, manifest) {
  for (const asset of Object.values(manifest.backgrounds ?? {})) copyAsset(rootDir, gameDir, asset, 'backgrounds')
  for (const asset of Object.values(manifest.sprites ?? {})) copyAsset(rootDir, gameDir, asset, 'characters')
  for (const asset of Object.values(manifest.cinematics ?? {})) copyAsset(rootDir, gameDir, asset, 'cinematics')
}

function copyAsset(rootDir, gameDir, asset, folder) {
  const source = path.join(rootDir, 'public', asset.src)
  const targetDir = path.join(gameDir, 'images', folder)
  mkdirSync(targetDir, { recursive: true })
  copyFileSync(source, path.join(targetDir, path.basename(asset.src)))
}

function firstQuestScriptPath(world, storyId) {
  if (storyId) {
    const quest = world.quests?.[storyId]
    if (quest?.scriptPath) return quest.scriptPath
  }
  const firstQuest = Object.values(world.quests ?? {})[0]
  if (!firstQuest?.scriptPath) throw new Error(`No quest scripts found for ${world.id}`)
  return firstQuest.scriptPath
}

function speakerName(script, speaker) {
  const character = script.characters?.[speaker.characterId]
  return character?.displayNames?.chinese ?? character?.displayNames?.english ?? speaker.characterId
}

function buildOptionsRpy(script) {
  return [
    '# Generated RenPy options for the Chunky Chinese prototype.',
    `define config.version = ${pythonString(script.contentVersion ?? 'prototype')}`,
    'define config.save_directory = "chunky-renpy-prototype"',
    'define config.window_title = "Chunky Chinese"',
    'define config.webaudio_required_types = [ "audio/mpeg" ]',
    '',
  ].join('\n')
}

function buildProgressiveDownload() {
  return [
    '# RenPyWeb progressive download rules.',
    '- image game/images/backgrounds/**',
    '+ image game/images/characters/**',
    '+ image game/images/cinematics/**',
    '+ voice game/audio/**',
    '',
  ].join('\n')
}

function buildReadme(script) {
  return [
    `# ${script.title} RenPy Prototype`,
    '',
    'Generated from the Chunky Chinese Visual Novel JSON source.',
    '',
    'Build this project with the RenPy launcher or CLI, then copy the generated web export to:',
    '',
    '```text',
    'public/renpy/just-friends',
    '```',
    '',
  ].join('\n')
}

function renpyLabel(id) {
  return `node_${renpyName(id)}`
}

function renpyName(id) {
  return String(id).replace(/[^A-Za-z0-9_]/g, '_').replace(/^([0-9])/, '_$1')
}

function pythonString(value) {
  return JSON.stringify(String(value))
}

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, 'utf8'))
}
