import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import type { Episode } from '../src/game/model'
const episodes = JSON.parse(readFileSync(new URL('../stories/chengdu/episodes.json', import.meta.url), 'utf8')) as Episode[]
async function open(page: Page, index=0) {
  await page.goto('./')
  await page.getByRole('button',{name:'Game',exact:true}).click()
  await page.locator('.game-card').nth(index).getByRole('button').click()
  await page.getByRole('button',{name:/^(Enter the neighbourhood|Continue conversation)$/}).click()
  return page.frameLocator('iframe[title*="playable Twine"]')
}
test('three Chinese choices then a longer builder in every episode; resume, support and replay',async({page},info)=>{
  test.setTimeout(150000)
  for(const [index,ep] of episodes.entries()) {
    const f=await open(page,index)
    for(let i=0;i<3;i++) {
      await f.getByRole('button',{name:'Show all',exact:true}).click()
      await expect(f.locator('.reply-option')).toHaveCount(3)
      await expect(f.locator('.reply-option .pinyin')).toHaveCount(3)
      await expect(f.locator('.goal-clue')).toBeVisible()
      if(index===0&&i===0) {
        await page.screenshot({path:info.outputPath('conversation.png'),fullPage:true})
        await f.locator('[data-key="option-1"]').click()
        await expect(f.locator('[role="status"]')).toContainText('asking')
        await expect(f.getByRole('button',{name:'Continue',exact:true})).toHaveCount(0)
      }
      await f.locator('[data-key="option-0"]').click()
      await expect(f.locator('.response .chinese')).toBeVisible()
      await f.getByRole('button',{name:'Continue',exact:true}).click()
    }
    await f.getByRole('button',{name:'Show all',exact:true}).click()
    await expect(f.locator('.chunks button')).toHaveCount(8)
    const order=await f.locator('.chunks button').evaluateAll(bs=>bs.map(b=>(b as HTMLElement).dataset.key))
    expect(order).not.toEqual(Array.from({length:8},(_,i)=>`tile-${7-i}`))
    await f.locator('[data-key="tile-0"]').click()
    await page.getByRole('button',{name:'← Game library'}).click()
    await page.locator('.game-card').nth(index).getByRole('button').click()
    await page.getByRole('button',{name:'Continue conversation',exact:true}).click()
    await expect(f.locator('.sentence button')).toHaveCount(1)
    expect(await f.locator('.chunks button').evaluateAll(bs=>bs.map(b=>(b as HTMLElement).dataset.key))).toEqual(order)
    for(let n=1;n<ep.scenes[3].choices[0].simple.chunks.length;n++)await f.locator(`[data-key="tile-${n}"]`).click()
    await f.getByRole('button',{name:'Check',exact:true}).click()
    await f.getByRole('button',{name:'Finish episode',exact:true}).click()
    await expect(f.getByRole('heading',{name:'Things I can now say'})).toBeVisible()
    await expect(f.getByText('Independently',{exact:true})).toHaveCount(index===0?3:4)
    await expect(f.getByText('With support',{exact:true})).toHaveCount(index===0?1:0)
    await f.getByRole('button',{name:'Back to Game',exact:true}).click()
  }
  const records=await page.evaluate(()=>Object.entries(localStorage).filter(([k])=>k.startsWith('chunky-game:')&&k.endsWith(':first')))
  expect(records).toHaveLength(3)
  await page.locator('.game-card').first().getByRole('button').click()
  await page.getByRole('button',{name:'Replay from the beginning',exact:true}).click()
  expect(await page.evaluate(()=>Object.entries(localStorage).filter(([k])=>k.startsWith('chunky-game:')&&k.endsWith(':first')))).toEqual(records)
})
test('scaffolding settings persist across reload, new episodes and resume',async({page})=>{
  let f=await open(page)
  await f.getByRole('button',{name:'Show all',exact:true}).click()
  await f.locator('summary').filter({hasText:'Game settings'}).click()
  await f.getByRole('button',{name:'Pinyin: on',exact:true}).click()
  await f.getByRole('button',{name:'English clues: on',exact:true}).click()
  await expect(f.locator('.pinyin')).toHaveCount(0)
  await expect(f.locator('.goal-clue')).toHaveCount(0)
  f=await open(page)
  await expect(f.locator('.pinyin')).toHaveCount(0)
  await expect(f.locator('.goal-clue')).toHaveCount(0)
  await page.getByRole('button',{name:'← Game library'}).click()
  await page.locator('.game-settings summary').click()
  await expect(page.getByLabel('Show pinyin by default')).not.toBeChecked()
  await expect(page.getByLabel('Show English goal clues by default')).not.toBeChecked()
  await page.getByLabel('Show pinyin by default').check()
  await page.getByLabel('Show English goal clues by default').check()
  f=await open(page,1)
  await f.getByRole('button',{name:'Show all',exact:true}).click()
  await expect(f.locator('.goal-clue')).toBeVisible()
  await expect(f.locator('.reply-option .pinyin')).toHaveCount(3)
})
test('controller choices, missing artwork, reduced motion and wrong-frame rejection',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.route('**/characters.webp',r=>r.abort())
  const f=await open(page)
  await expect(f.getByText(/Ms Lin · my neighbour/)).toBeVisible()
  const key='chunky-game:v1:guest:neighbour:2'
  const before=await page.evaluate(k=>localStorage.getItem(k),key)
  await page.evaluate(()=>{const frame=document.querySelector('iframe')!;const channel=new URL(frame.src).hash.split('channel=')[1];window.postMessage({protocol:'chunky-game-v1',channel,type:'action',revision:0,action:{type:'showAll'}},location.origin)})
  expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(before)
  await f.getByRole('button',{name:'Show all',exact:true}).click()
  const shortcut=await f.locator('[data-key="option-0"]').getAttribute('data-shortcut')
  await page.keyboard.press(shortcut!)
  await expect(f.getByRole('button',{name:'Continue',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Window',exact:true}).click()
  await expect(f.getByRole('button',{name:'Continue',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})
test('opened episode and all Mandarin options replay offline',async({page,context})=>{
  test.skip(process.env.GAME_PRODUCTION_TEST!=='1')
  let f=await open(page)
  await expect(page.getByText(/Episode downloaded/)).toBeVisible()
  await page.waitForFunction(()=>Boolean(navigator.serviceWorker.controller))
  await f.getByRole('button',{name:'Show all',exact:true}).click()
  await expect(f.locator('.reply-option')).toHaveCount(3)
  await context.setOffline(true)
  f=await open(page)
  await expect(f.locator('.reply-option')).toHaveCount(3)
  const durations=await page.evaluate(async()=>{
    const cache=await caches.open('chunky-game-v1')
    const urls=(await cache.keys()).filter(r=>r.url.includes('/game/v2/')&&r.url.endsWith('.m4a'))
    return Promise.all(urls.map(r=>new Promise<number>((resolve,reject)=>{const a=new Audio(r.url);a.preload='metadata';const timer=setTimeout(()=>reject(new Error('Audio timeout')),10000);a.onloadedmetadata=()=>{clearTimeout(timer);resolve(a.duration)};a.onerror=()=>{clearTimeout(timer);reject(new Error(r.url))}})))
  })
  expect(durations.length).toBeGreaterThan(12)
  expect(durations.every(n=>n>0&&Number.isFinite(n))).toBe(true)
})
