import {expect,test,type Page} from '@playwright/test'
test.use({serviceWorkers:'block'})
async function openLibrary(page: Page) {
 const dashboard=page.locator('.dashboard-mode-card.reading-texts-start')
 const library=page.getByRole('button',{name:'Library',exact:true})
 const add=page.getByRole('button',{name:'Add a text',exact:true})
 await expect(async()=>{
  if(await add.isVisible()) return
  if(await dashboard.isVisible()) await dashboard.click()
  if(await library.isVisible()) await library.click({timeout:1000})
  await expect(add).toBeVisible({timeout:1000})
 }).toPass({timeout:15000})
}
const paired = '我想看书。\nI want to read.\n你好。\nHello.'
test('paste and upload respect length, category and temporary retention',async({page},testInfo)=>{
 await page.goto('/')
 await openLibrary(page)
 await page.getByRole('button',{name:'Add a text',exact:true}).click()
 await page.getByRole('button',{name:'Paste text',exact:true}).click()
 await page.getByLabel('Text title',{exact:true}).fill('Temporary walk')
 await page.getByLabel('Text category',{exact:true}).fill('LMS')
 await page.getByLabel('Keep text',{exact:true}).selectOption('temporary')
 await page.getByLabel('Chinese and English text',{exact:true}).fill('Hello.\n你好。')
 await page.getByRole('button',{name:'Add pasted text'}).click()
 await expect(page.getByText(/Line 1 should be Chinese/)).toBeVisible()
 await page.getByLabel('Chinese and English text',{exact:true}).fill(paired)
 await page.getByRole('button',{name:'Add pasted text'}).click()
 await expect(page.getByText('Temporary walk is ready in Reading.')).toBeVisible()
 await page.getByRole('button',{name:'Close text creator'}).click()
 await page.getByLabel('Category',{exact:true}).selectOption('Legendary Moonlight Sculptor')
 await page.getByRole('button',{name:'Short',exact:true}).click()
 const temporary=page.locator('.reading-library-book',{hasText:'Temporary walk'})
 await expect(temporary).toContainText('Temporary')
 await temporary.getByRole('button',{name:'Start',exact:true}).click()
 await expect(page.locator('.reader-translation')).toContainText('I want to read.')
 await page.getByRole('button',{name:'Library',exact:true}).click()
 await page.reload()
 await openLibrary(page)
 await expect(page.locator('.reading-library-book',{hasText:'Temporary walk'})).toHaveCount(0)
 await page.getByRole('button',{name:'Add a text',exact:true}).click()
 await page.getByLabel('Text length',{exact:true}).selectOption('long')
 await page.getByLabel('Text category',{exact:true}).fill('Boy who lived')
 await page.getByLabel('Keep text',{exact:true}).selectOption('temporary')
 await page.getByLabel('Upload bilingual TXT').setInputFiles({name:'Another chapter.txt',mimeType:'text/plain',buffer:Buffer.from(paired)})
 await expect(page.getByText('Another chapter is ready in Reading.')).toBeVisible()
 await page.getByRole('button',{name:'Close text creator'}).click()
 const saved=page.locator('.reading-library-book',{hasText:'Another chapter'})
 await saved.getByText('Story options',{exact:true}).click()
 await saved.getByRole('button',{name:'Keep permanently'}).click()
 await expect(saved).not.toContainText('Temporary')
 await page.reload()
 await openLibrary(page)
 await page.getByRole('button',{name:'Long',exact:true}).click()
 await page.getByLabel('Category',{exact:true}).selectOption('Harry Potter · The Boy Who Lived')
 await expect(saved).toBeVisible()
 await page.getByLabel('Find a text').fill('not a title')
 await expect(saved).toHaveCount(0)
 await page.getByLabel('Find a text').fill('Another')
 await expect(saved).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:testInfo.outputPath('organized-library.png'),fullPage:true})
})
test('AI generation receives the same placement and permanent storage choice',async({page})=>{
 await page.goto('/')
 await expect(page.locator('.dashboard-mode-card.reading-texts-start')).toBeVisible()
 await page.evaluate(async()=>{
  await new Promise<void>((resolve,reject)=>{const r=indexedDB.open('chunky-chinese-vocab');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result;const tx=db.transaction(['settings','vocabWords'],'readwrite');const words=tx.objectStore('vocabWords');const all=words.getAll();all.onsuccess=()=>{for(const word of all.result.slice(0,30))words.put({...word,status:'known',fsrsState:'Review',fsrsIntervalDays:30,fsrsDueAt:'2099-01-01T00:00:00.000Z'})};tx.objectStore('settings').put({openRouterApiKey:'test-only-placeholder',generateCover:false,generateAudio:false},'aiStorySettings');tx.oncomplete=()=>{db.close();resolve()}}})
 })
 await page.route('https://openrouter.ai/api/v1/chat/completions',route=>route.fulfill({json:{choices:[{message:{content:JSON.stringify({title:'AI classroom',sentences:[{chinese:'你好。',english:'Hello.'}],unavoidableNewWords:[]})}}]}}))
 await page.reload()
 await openLibrary(page)
 await page.getByRole('button',{name:'Add a text',exact:true}).click()
 await page.getByRole('button',{name:'Generate with AI',exact:true}).click()
 await page.getByLabel('Text category',{exact:true}).fill('School')
 await page.getByLabel('Text length',{exact:true}).selectOption('short')
 await page.getByLabel(/^Prompt/).fill('A short classroom conversation')
 await page.getByRole('button',{name:'Generate Story',exact:true}).click()
 await expect(page.getByRole('button',{name:'Read it',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Close text creator'}).click()
 await page.getByLabel('Category',{exact:true}).selectOption('School')
 await expect(page.locator('.reading-library-book',{hasText:'AI classroom'})).toBeVisible()
})
