import { expect, test } from '@playwright/test'

test.use({ serviceWorkers: 'block' })

test('library filters books in place and keeps creation out of the reading flow', async ({ page }, testInfo) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.locator('.dashboard-mode-card.reading-texts-start').click()
  await expect(page.getByRole('heading', { name: 'Reading', exact: true })).toBeVisible()
  await expect(page.locator('.reading-library-book').first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Generate Story', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Novels', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reading', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start Meditative Scripture · 默想经文', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Stories', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start Meditative Scripture · 默想经文', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'All', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start Meditative Scripture · 默想经文', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Create a story', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Generate Story', exact: true })).toBeVisible()
  await page.getByLabel('Upload bilingual TXT').setInputFiles({ name: 'A quiet walk.txt', mimeType: 'text/plain', buffer: Buffer.from('我想去学校。\nI want to go to school.\n我们一起走。\nWe walk together.') })
  await expect(page.getByText(/A quiet walk is ready in Reading/)).toBeVisible()
  await page.getByRole('button', { name: 'Close story creator' }).click()
  await page.getByRole('button', { name: 'Stories', exact: true }).click()
  const story = page.locator('.reading-library-book', { hasText: 'A quiet walk' })
  await expect(story).toBeVisible()
  await story.getByText('Story options', { exact: true }).click()
  await expect(story.getByRole('button', { name: 'Write next chapter' })).toBeVisible()
  await page.getByRole('button', { name: 'All', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Generate Story', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('simple-library.png'), fullPage: true })
  await page.getByRole('button', { name: 'Start Meditative Scripture · 默想经文', exact: true }).click()
  await expect(page.locator('.reader-page-meta')).toContainText('Meditative Scripture')
})

test('reading aids persist independently and transport stays consistent', async ({ page }, testInfo) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.locator('.dashboard-mode-card.reading-texts-start').click()
  await page.getByRole('button', { name: 'Start Meditative Scripture · 默想经文', exact: true }).click()
  const controls = page.locator('.reader-listening-controls')
  await expect(controls.getByRole('button')).toHaveCount(3)
  await expect(controls.getByRole('button').nth(0)).toHaveAccessibleName('Previous sentence')
  await expect(controls.getByRole('button').nth(1)).toHaveAccessibleName(/Play listening|Pause listening/)
  await expect(controls.getByRole('button').nth(2)).toHaveAccessibleName(/Next sentence/)
  await expect(page.locator('.reader-interlinear-pinyin').first()).toBeVisible()
  await page.getByRole('button', { name: 'Pinyin', exact: true }).click()
  await expect(page.locator('.reader-interlinear-pinyin')).toHaveCount(0)
  await expect(page.locator('.reader-interlinear-gloss').first()).toBeVisible()
  await page.getByRole('button', { name: 'Meaning', exact: true }).click()
  await expect(page.locator('.reader-interlinear-gloss')).toHaveCount(0)
  await expect(page.locator('.reader-translation')).toHaveCount(0)
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reading', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Pinyin', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: 'Meaning', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Pinyin', exact: true }).click()
  await expect(page.locator('.reader-interlinear-pinyin').first()).toBeVisible()
  await expect(page.locator('.reader-translation')).toHaveCount(0)
  await page.getByRole('button', { name: 'Meaning', exact: true }).click()
  await page.getByLabel('Speed').selectOption('0.8')
  await expect(page.getByLabel('Repeats')).toHaveCount(0)
  await page.getByRole('button', { name: 'Reader menu' }).click()
  await page.getByLabel('Repeats').selectOption('2')
  await expect(page.getByLabel('Speaking pause')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Back to library' })).toBeVisible()
  await page.locator('.sentence-menu-backdrop').click({ position: { x: 5, y: 5 } })
  await controls.getByRole('button').nth(2).click()
  await expect(controls.getByRole('button').nth(0)).toBeEnabled()
  await controls.getByRole('button').nth(0).click()
  await expect(page.locator('.reader-page-meta')).toContainText('Sentence 1 /')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('simple-reader.png'), fullPage: true })
})
