# Generated by scripts/vn-renpy/convert.mjs. Edit the Chunky VN JSON source instead.

define config.name = "Chunky Chinese - RenPy Prototype"
define narrator = Character(None)

transform chunky_far_left:
    xalign 0.08
    yalign 1.0

transform chunky_far_right:
    xalign 0.92
    yalign 1.0

init python:
    import json

    def chunky_event(name, payload=None):
        if payload is None:
            payload = {}
        payload["type"] = name
        payload["storyId"] = "just-friends-story"
        if renpy.emscripten:
            renpy.emscripten.run_script(
                "window.parent && window.parent.postMessage(" + json.dumps({"source": "chunky-renpy", "payload": payload}) + ", '*')"
            )

    def chunky_line(node_id, text):
        chunky_event("lineChanged", {"nodeId": node_id, "text": text})

    def chunky_choice(node_id, choice_id, text):
        chunky_event("choiceSelected", {"nodeId": node_id, "choiceId": choice_id, "text": text})

    def chunky_complete(node_id, quest_id, outcome_id):
        chunky_event("questComplete", {"nodeId": node_id, "questId": quest_id, "outcomeId": outcome_id})

image bg_campus_day = "images/backgrounds/campus-day.webp"
image bg_bookstore_evening = "images/backgrounds/bookstore-evening.webp"
image bg_snack_shop_night = "images/backgrounds/snack-shop-night.webp"
image bg_restaurant_night = "images/backgrounds/restaurant-night.webp"
image bg_family_home = "images/backgrounds/family-home.webp"
image spr_dapeng_neutral = "images/characters/dapeng-neutral.webp"
image spr_dapeng_angry = "images/characters/dapeng-angry.webp"
image spr_wendong_neutral = "images/characters/wendong-neutral.webp"
image spr_wendong_worried = "images/characters/wendong-worried.webp"
image spr_zixin_neutral = "images/characters/zixin-neutral.webp"
image spr_zixin_smile = "images/characters/zixin-smile.webp"

label start:
    $ chunky_event("ready", {"initialNodeId": "jf-001"})
    jump node_jf_001

label node_jf_001:
    scene bg_campus_day
    show spr_dapeng_neutral at left
    show spr_wendong_neutral at right
    $ chunky_line("jf-001", "钱大朋和谢文东都是中山大学的大学生，今年是他们大学的第二年。")
    narrator "钱大朋和谢文东都是中山大学的大学生，今年是他们大学的第二年。"
    jump node_jf_002

label node_jf_002:
    $ chunky_line("jf-002", "他们天天一起去吃饭，一起去看书，两个人是很好的朋友。")
    narrator "他们天天一起去吃饭，一起去看书，两个人是很好的朋友。"
    jump node_jf_003

label node_jf_003:
    $ chunky_line("jf-003", "谢文东的爸爸妈妈开饭店。")
    narrator "谢文东的爸爸妈妈开饭店。"
    jump node_jf_004

label node_jf_004:
    $ chunky_line("jf-004", "谢文东有时候会带钱大朋去饭店吃饭。")
    narrator "谢文东有时候会带钱大朋去饭店吃饭。"
    jump node_jf_005

label node_jf_005:
    $ chunky_line("jf-005", "谢文东的爸爸妈妈都见过钱大朋。")
    narrator "谢文东的爸爸妈妈都见过钱大朋。"
    jump node_jf_006

label node_jf_006:
    $ chunky_line("jf-006", "钱大朋有时候也会开车带谢文东回家。")
    narrator "钱大朋有时候也会开车带谢文东回家。"
    jump node_jf_007

label node_jf_007:
    $ chunky_line("jf-007", "钱大朋不喜欢吃大学的饭，天天都出去吃。")
    narrator "钱大朋不喜欢吃大学的饭，天天都出去吃。"
    jump node_jf_008

label node_jf_008:
    $ chunky_line("jf-008", "钱大朋的爸爸妈妈很有钱，每个月都给儿子很多钱。")
    narrator "钱大朋的爸爸妈妈很有钱，每个月都给儿子很多钱。"
    jump node_jf_009

label node_jf_009:
    $ chunky_line("jf-009", "“大朋，你有车，天天开车来大学。")
    narrator "“大朋，你有车，天天开车来大学。"
    jump node_jf_010

label node_jf_010:
    $ chunky_line("jf-010", "你很开心吧！”")
    narrator "你很开心吧！”"
    jump node_jf_011

label node_jf_011:
    $ chunky_line("jf-011", "文东和大朋说。")
    narrator "文东和大朋说。"
    jump node_jf_012

label node_jf_012:
    $ chunky_line("jf-012", "“我一点也不开心！")
    narrator "“我一点也不开心！"
    jump node_jf_013

label node_jf_013:
    $ chunky_line("jf-013", "我从小到大都跟我爸妈在一起，我做什么他们都要问。”")
    narrator "我从小到大都跟我爸妈在一起，我做什么他们都要问。”"
    jump node_jf_014

label node_jf_014:
    $ chunky_line("jf-014", "钱大朋不开心地说，“我一点也不喜欢这样的家。”")
    narrator "钱大朋不开心地说，“我一点也不喜欢这样的家。”"
    jump node_jf_015

label node_jf_015:
    $ chunky_line("jf-015", "“他们关心你。")
    narrator "“他们关心你。"
    jump node_jf_016

label node_jf_016:
    $ chunky_line("jf-016", "那样不好吗？”")
    narrator "那样不好吗？”"
    jump node_jf_017

label node_jf_017:
    $ chunky_line("jf-017", "谢文东问。")
    narrator "谢文东问。"
    jump node_jf_018

label node_jf_018:
    $ chunky_line("jf-018", "“我知道他们关心我。")
    narrator "“我知道他们关心我。"
    jump node_jf_019

label node_jf_019:
    $ chunky_line("jf-019", "可是，有时候‘太关心了’，我不知道怎么跟他们说。”")
    narrator "可是，有时候‘太关心了’，我不知道怎么跟他们说。”"
    jump node_jf_020

label node_jf_020:
    $ chunky_line("jf-020", "钱大朋说，“我回家的时候，我妈天天问我有没有女朋友。”")
    narrator "钱大朋说，“我回家的时候，我妈天天问我有没有女朋友。”"
    jump node_jf_021

label node_jf_021:
    $ chunky_line("jf-021", "“你怎么说？”")
    narrator "“你怎么说？”"
    jump node_jf_022

label node_jf_022:
    $ chunky_line("jf-022", "“我不知道怎么说。")
    narrator "“我不知道怎么说。"
    jump node_jf_023

label node_jf_023:
    $ chunky_line("jf-023", "说有，我妈会马上想和我的女朋友见面。")
    narrator "说有，我妈会马上想和我的女朋友见面。"
    jump node_jf_024

label node_jf_024:
    $ chunky_line("jf-024", "说没有，我妈会叫我去见一个女生，跟那个女生去吃饭什么的。")
    narrator "说没有，我妈会叫我去见一个女生，跟那个女生去吃饭什么的。"
    jump node_jf_025

label node_jf_025:
    $ chunky_line("jf-025", "可是，我一点也不喜欢那个女生。")
    narrator "可是，我一点也不喜欢那个女生。"
    jump node_jf_026

label node_jf_026:
    $ chunky_line("jf-026", "我也不想和她见面。”")
    narrator "我也不想和她见面。”"
    jump node_jf_027

label node_jf_027:
    $ chunky_line("jf-027", "“那，你妈知不知道你不喜欢那个女生？”")
    narrator "“那，你妈知不知道你不喜欢那个女生？”"
    jump node_jf_028

label node_jf_028:
    $ chunky_line("jf-028", "“她知道，我说过很多次，可是，那个女生是一个大学生，她是我爸的一个好朋友的女儿。")
    narrator "“她知道，我说过很多次，可是，那个女生是一个大学生，她是我爸的一个好朋友的女儿。"
    jump node_jf_029

label node_jf_029:
    $ chunky_line("jf-029", "我爸很喜欢。")
    narrator "我爸很喜欢。"
    jump node_jf_030

label node_jf_030:
    $ chunky_line("jf-030", "我一点也不喜欢。”")
    narrator "我一点也不喜欢。”"
    jump node_jf_031

label node_jf_031:
    $ chunky_line("jf-031", "谢文东听了笑笑，不知道说什么。")
    narrator "谢文东听了笑笑，不知道说什么。"
    jump node_jf_032

label node_jf_032:
    scene bg_campus_day
    show spr_dapeng_neutral at left
    show spr_wendong_neutral at right
    $ chunky_line("jf-032", "“大朋，我们大学那么多好看的女生，你没有喜欢的吗？”")
    narrator "“大朋，我们大学那么多好看的女生，你没有喜欢的吗？”"
    jump node_jf_033

label node_jf_033:
    $ chunky_line("jf-033", "吃饭的时候，谢文东问。")
    narrator "吃饭的时候，谢文东问。"
    jump node_jf_034

label node_jf_034:
    $ chunky_line("jf-034", "大朋看看文东，笑了笑：“你看到什么了？”")
    narrator "大朋看看文东，笑了笑：“你看到什么了？”"
    jump node_jf_035

label node_jf_035:
    $ chunky_line("jf-035", "“这几天，我看你都在看周子心。")
    narrator "“这几天，我看你都在看周子心。"
    jump node_jf_036

label node_jf_036:
    $ chunky_line("jf-036", "上次，我跟你说话你都没有听见。")
    narrator "上次，我跟你说话你都没有听见。"
    jump node_jf_037

label node_jf_037:
    $ chunky_line("jf-037", "你是不是喜欢她？”")
    narrator "你是不是喜欢她？”"
    jump node_jf_038

label node_jf_038:
    $ chunky_line("jf-038", "“我喜欢她，那又怎么样？”")
    narrator "“我喜欢她，那又怎么样？”"
    jump node_jf_039

label node_jf_039:
    $ chunky_line("jf-039", "钱大朋笑了。")
    narrator "钱大朋笑了。"
    jump node_jf_040

label node_jf_040:
    $ chunky_line("jf-040", "文东看看大朋，没有笑：“我也喜欢她。”")
    narrator "文东看看大朋，没有笑：“我也喜欢她。”"
    jump node_jf_041

label node_jf_041:
    $ chunky_line("jf-041", "大朋一下子不笑了，也不吃了：“不是吧？")
    narrator "大朋一下子不笑了，也不吃了：“不是吧？"
    jump node_jf_042

label node_jf_042:
    $ chunky_line("jf-042", "从什么时候……我怎么一点也不知道？”")
    narrator "从什么时候……我怎么一点也不知道？”"
    jump node_jf_043

label node_jf_043:
    $ chunky_line("jf-043", "“我和她都喜欢看书，我在书店见过她很多次。")
    narrator "“我和她都喜欢看书，我在书店见过她很多次。"
    jump node_jf_044

label node_jf_044:
    $ chunky_line("jf-044", "她是一个好女生，也很好看……谁会不喜欢？”")
    narrator "她是一个好女生，也很好看……谁会不喜欢？”"
    jump node_jf_045

label node_jf_045:
    $ chunky_line("jf-045", "“那，你跟她说了吗？”")
    narrator "“那，你跟她说了吗？”"
    jump node_jf_046

label node_jf_046:
    $ chunky_line("jf-046", "大朋小心地问。")
    narrator "大朋小心地问。"
    jump node_jf_047

label node_jf_047:
    $ chunky_line("jf-047", "“没有，她不知道我喜欢她……”文东不说了。")
    narrator "“没有，她不知道我喜欢她……”文东不说了。"
    jump node_jf_048

label node_jf_048:
    $ chunky_line("jf-048", "“我也没跟她说。”")
    narrator "“我也没跟她说。”"
    jump node_jf_049

label node_jf_049:
    $ chunky_line("jf-049", "大朋说。")
    narrator "大朋说。"
    jump node_jf_050

label node_jf_050:
    $ chunky_line("jf-050", "“大朋，我们是不是好朋友？”")
    narrator "“大朋，我们是不是好朋友？”"
    jump node_jf_051

label node_jf_051:
    $ chunky_line("jf-051", "谢文东问。")
    narrator "谢文东问。"
    jump node_jf_052

label node_jf_052:
    $ chunky_line("jf-052", "“是，那又怎么样？")
    narrator "“是，那又怎么样？"
    jump node_jf_053

label node_jf_053:
    $ chunky_line("jf-053", "周子心不是你的女朋友，对不对？”")
    narrator "周子心不是你的女朋友，对不对？”"
    jump node_jf_054

label node_jf_054:
    $ chunky_line("jf-054", "大朋小心地问。")
    narrator "大朋小心地问。"
    jump node_jf_055

label node_jf_055:
    $ chunky_line("jf-055", "文东生气地看大朋：“你怎么能这样说？”")
    narrator "文东生气地看大朋：“你怎么能这样说？”"
    jump node_jf_056

label node_jf_056:
    $ chunky_line("jf-056", "大朋知道文东生气了。")
    narrator "大朋知道文东生气了。"
    jump node_jf_057

label node_jf_057:
    $ chunky_line("jf-057", "大朋跟他说：“好了好了，我知道你要说什么。")
    narrator "大朋跟他说：“好了好了，我知道你要说什么。"
    jump node_jf_058

label node_jf_058:
    $ chunky_line("jf-058", "我们是好朋友，我是不会跟你喜欢的女生一起出去的。”")
    narrator "我们是好朋友，我是不会跟你喜欢的女生一起出去的。”"
    jump node_jf_059

label node_jf_059:
    $ chunky_line("jf-059", "文东笑了：“好！")
    narrator "文东笑了：“好！"
    jump node_jf_060

label node_jf_060:
    $ chunky_line("jf-060", "我也是不会跟她一起出去的！”")
    narrator "我也是不会跟她一起出去的！”"
    jump node_jf_061

label node_jf_061:
    scene bg_bookstore_evening
    show spr_dapeng_neutral at left
    show spr_zixin_smile at right
    $ chunky_line("jf-061", "星期四晚上，很多学生都在一起说话。")
    narrator "星期四晚上，很多学生都在一起说话。"
    jump node_jf_062

label node_jf_062:
    $ chunky_line("jf-062", "谢文东不在。")
    narrator "谢文东不在。"
    jump node_jf_063

label node_jf_063:
    $ chunky_line("jf-063", "两个男生问钱大朋：“大朋，你是不是喜欢周子心？”")
    narrator "两个男生问钱大朋：“大朋，你是不是喜欢周子心？”"
    jump node_jf_064

label node_jf_064:
    $ chunky_line("jf-064", "“没有……你们听谁说的？”")
    narrator "“没有……你们听谁说的？”"
    jump node_jf_065

label node_jf_065:
    $ chunky_line("jf-065", "大朋说。")
    narrator "大朋说。"
    jump node_jf_066

label node_jf_066:
    $ chunky_line("jf-066", "“没有人说，可是，大家都知道了。”")
    narrator "“没有人说，可是，大家都知道了。”"
    jump node_jf_067

label node_jf_067:
    $ chunky_line("jf-067", "两个男生笑了。")
    narrator "两个男生笑了。"
    jump node_jf_068

label node_jf_068:
    $ chunky_line("jf-068", "“好了好了，不要笑了。")
    narrator "“好了好了，不要笑了。"
    jump node_jf_069

label node_jf_069:
    $ chunky_line("jf-069", "对，我是喜欢她。")
    narrator "对，我是喜欢她。"
    jump node_jf_070

label node_jf_070:
    $ chunky_line("jf-070", "那又怎么样？”")
    narrator "那又怎么样？”"
    jump node_jf_071

label node_jf_071:
    $ chunky_line("jf-071", "钱大朋也笑了一下，“我出去走走。”")
    narrator "钱大朋也笑了一下，“我出去走走。”"
    jump node_jf_072

label node_jf_072:
    $ chunky_line("jf-072", "这时候，钱大朋看到了周子心。")
    narrator "这时候，钱大朋看到了周子心。"
    jump node_jf_073

label node_jf_073:
    $ chunky_line("jf-073", "“周子心，这么晚了，你一个人去哪儿？”")
    narrator "“周子心，这么晚了，你一个人去哪儿？”"
    jump node_jf_074

label node_jf_074:
    $ chunky_line("jf-074", "钱大朋问她。")
    narrator "钱大朋问她。"
    jump node_jf_075

label node_jf_075:
    $ chunky_line("jf-075", "周子心看了看：“钱大朋？”")
    narrator "周子心看了看：“钱大朋？”"
    jump node_jf_076

label node_jf_076:
    $ chunky_line("jf-076", "她笑了一下，“我要去书店。”")
    narrator "她笑了一下，“我要去书店。”"
    jump node_jf_077

label node_jf_077:
    $ chunky_line("jf-077", "“那个很大的书店？”")
    narrator "“那个很大的书店？”"
    jump node_jf_078

label node_jf_078:
    $ chunky_line("jf-078", "钱大朋问。")
    narrator "钱大朋问。"
    jump node_jf_079

label node_jf_079:
    $ chunky_line("jf-079", "“对，这里有车可以去那个很大的书店。”")
    narrator "“对，这里有车可以去那个很大的书店。”"
    jump node_jf_080

label node_jf_080:
    $ chunky_line("jf-080", "周子心笑了笑。")
    narrator "周子心笑了笑。"
    jump node_jf_081

label node_jf_081:
    $ chunky_line("jf-081", "“你回来的时候都要9点多了。")
    narrator "“你回来的时候都要9点多了。"
    jump node_jf_082

label node_jf_082:
    $ chunky_line("jf-082", "你一个人回来不行……我开车带你去吧。”")
    narrator "你一个人回来不行……我开车带你去吧。”"
    jump node_jf_083

label node_jf_083:
    $ chunky_line("jf-083", "钱大朋笑笑说，“周子心，我们走吧。")
    narrator "钱大朋笑笑说，“周子心，我们走吧。"
    jump node_jf_084

label node_jf_084:
    $ chunky_line("jf-084", "车在那里。”")
    narrator "车在那里。”"
    jump node_jf_085

label node_jf_085:
    scene bg_bookstore_evening
    show spr_dapeng_angry at left
    show spr_zixin_neutral at right
    $ chunky_line("jf-085", "谢文东晚上在外面和朋友吃饭，回来的时候，他看到了钱大朋在车里，车里还有周子心。")
    narrator "谢文东晚上在外面和朋友吃饭，回来的时候，他看到了钱大朋在车里，车里还有周子心。"
    jump node_jf_086

label node_jf_086:
    $ chunky_line("jf-086", "“钱大朋，你不是我的朋友！”")
    narrator "“钱大朋，你不是我的朋友！”"
    jump node_jf_087

label node_jf_087:
    $ chunky_line("jf-087", "文东大叫。")
    narrator "文东大叫。"
    jump node_jf_088

label node_jf_088:
    $ chunky_line("jf-088", "可是，大朋什么也没听到，开车走了。")
    narrator "可是，大朋什么也没听到，开车走了。"
    jump node_jf_089

label node_jf_089:
    $ chunky_line("jf-089", "文东很生气，他马上叫了车，也去了那个书店。")
    narrator "文东很生气，他马上叫了车，也去了那个书店。"
    jump node_jf_090

label node_jf_090:
    $ chunky_line("jf-090", "到了书店，周子心跟钱大朋说：“你去哪里？”")
    narrator "到了书店，周子心跟钱大朋说：“你去哪里？”"
    jump node_jf_091

label node_jf_091:
    $ chunky_line("jf-091", "“我去外面走走吧。”")
    narrator "“我去外面走走吧。”"
    jump node_jf_092

label node_jf_092:
    $ chunky_line("jf-092", "钱大朋说。")
    narrator "钱大朋说。"
    jump node_jf_093

label node_jf_093:
    $ chunky_line("jf-093", "“过一会儿，我开车带你回去。”")
    narrator "“过一会儿，我开车带你回去。”"
    jump node_jf_094

label node_jf_094:
    $ chunky_line("jf-094", "周子心说：“你和我一起去吧。")
    narrator "周子心说：“你和我一起去吧。"
    jump node_jf_095

label node_jf_095:
    $ chunky_line("jf-095", "你可以看看有没有你喜欢的书。”")
    narrator "你可以看看有没有你喜欢的书。”"
    jump node_jf_096

label node_jf_096:
    $ chunky_line("jf-096", "钱大朋想了想，和周子心一起去书店了。")
    narrator "钱大朋想了想，和周子心一起去书店了。"
    jump node_jf_097

label node_jf_097:
    $ chunky_line("jf-097", "谢文东看到他们去了书店，谢文东也去了书店。")
    narrator "谢文东看到他们去了书店，谢文东也去了书店。"
    jump node_jf_098

label node_jf_098:
    $ chunky_line("jf-098", "过了一会儿，周子心跟钱大朋说：“大朋，我们出去吃一点东西吧。”")
    narrator "过了一会儿，周子心跟钱大朋说：“大朋，我们出去吃一点东西吧。”"
    jump node_jf_099

label node_jf_099:
    $ chunky_line("jf-099", "他看了看周子心，说：“好。”")
    narrator "他看了看周子心，说：“好。”"
    jump node_jf_100

label node_jf_100:
    $ chunky_line("jf-100", "说完，大朋和周子心去了书店外面的小吃店。")
    narrator "说完，大朋和周子心去了书店外面的小吃店。"
    jump node_jf_101

label node_jf_101:
    scene bg_snack_shop_night
    show spr_dapeng_angry at left
    show spr_zixin_neutral at right
    $ chunky_line("jf-101", "在小吃店里，人不多。")
    narrator "在小吃店里，人不多。"
    jump node_jf_102

label node_jf_102:
    $ chunky_line("jf-102", "钱大朋说：“点你喜欢吃的小吃吧。")
    narrator "钱大朋说：“点你喜欢吃的小吃吧。"
    jump node_jf_103

label node_jf_103:
    $ chunky_line("jf-103", "这里的小吃都很好吃。”")
    narrator "这里的小吃都很好吃。”"
    jump node_jf_104

label node_jf_104:
    $ chunky_line("jf-104", "周子心笑了笑说：“谢谢你开车带我过来，你点吧。”")
    narrator "周子心笑了笑说：“谢谢你开车带我过来，你点吧。”"
    jump node_jf_105

label node_jf_105:
    $ chunky_line("jf-105", "这时候，钱大朋听到一个男生叫他：“钱大朋！”")
    narrator "这时候，钱大朋听到一个男生叫他：“钱大朋！”"
    jump node_jf_106

label node_jf_106:
    $ chunky_line("jf-106", "“谢文东？")
    narrator "“谢文东？"
    jump node_jf_107

label node_jf_107:
    $ chunky_line("jf-107", "你怎么在这里……”钱大朋说。")
    narrator "你怎么在这里……”钱大朋说。"
    jump node_jf_108

label node_jf_108:
    $ chunky_line("jf-108", "谢文东生气地看了看钱大朋：“你和周子心怎么会在一起……我们不是好朋友吗？”")
    narrator "谢文东生气地看了看钱大朋：“你和周子心怎么会在一起……我们不是好朋友吗？”"
    jump node_jf_109

label node_jf_109:
    $ chunky_line("jf-109", "“不是你想的那样。")
    narrator "“不是你想的那样。"
    jump node_jf_110

label node_jf_110:
    $ chunky_line("jf-110", "她要来书店，我开车带她来书店。”")
    narrator "她要来书店，我开车带她来书店。”"
    jump node_jf_111

label node_jf_111:
    $ chunky_line("jf-111", "“我都看到了！”")
    narrator "“我都看到了！”"
    jump node_jf_112

label node_jf_112:
    $ chunky_line("jf-112", "谢文东说，“你们两个在一起多长时间了？”")
    narrator "谢文东说，“你们两个在一起多长时间了？”"
    jump node_jf_113

label node_jf_113:
    $ chunky_line("jf-113", "“谢文东，你在说什么？”")
    narrator "“谢文东，你在说什么？”"
    jump node_jf_114

label node_jf_114:
    $ chunky_line("jf-114", "周子心马上说，“我没和钱大朋在一起，他也不是我男朋友。”")
    narrator "周子心马上说，“我没和钱大朋在一起，他也不是我男朋友。”"
    jump node_jf_115

label node_jf_115:
    $ chunky_line("jf-115", "“钱大朋，谢文东为什么那样说？”")
    narrator "“钱大朋，谢文东为什么那样说？”"
    jump node_jf_116

label node_jf_116:
    $ chunky_line("jf-116", "周子心问。")
    narrator "周子心问。"
    jump node_jf_117

label node_jf_117:
    $ chunky_line("jf-117", "钱大朋不知道对周子心说什么。")
    narrator "钱大朋不知道对周子心说什么。"
    jump node_jf_118

label node_jf_118:
    $ chunky_line("jf-118", "他看谢文东不说话，他也不说话。")
    narrator "他看谢文东不说话，他也不说话。"
    jump node_jf_119

label node_jf_119:
    $ chunky_line("jf-119", "周子心说：“好吧，要是你们都没什么要说的，那我走了。”")
    narrator "周子心说：“好吧，要是你们都没什么要说的，那我走了。”"
    jump node_jf_120

label node_jf_120:
    $ chunky_line("jf-120", "她走了。")
    narrator "她走了。"
    jump node_jf_121

label node_jf_121:
    $ chunky_line("jf-121", "谢文东说：“钱大朋，你怎么能这样做？")
    narrator "谢文东说：“钱大朋，你怎么能这样做？"
    jump node_jf_122

label node_jf_122:
    $ chunky_line("jf-122", "我们不是好朋友吗？”")
    narrator "我们不是好朋友吗？”"
    jump node_jf_123

label node_jf_123:
    $ chunky_line("jf-123", "“我做什么了？")
    narrator "“我做什么了？"
    jump node_jf_124

label node_jf_124:
    $ chunky_line("jf-124", "我什么也没做！”")
    narrator "我什么也没做！”"
    jump node_jf_125

label node_jf_125:
    $ chunky_line("jf-125", "钱大朋又说：“你为什么要来这里？”")
    narrator "钱大朋又说：“你为什么要来这里？”"
    jump node_jf_126

label node_jf_126:
    $ chunky_line("jf-126", "谢文东小心地说：“要是我没有来这里，谁知道你们会做什么……”“谢文东，你听我说，我和周子心不是男朋友和女朋友！”")
    narrator "谢文东小心地说：“要是我没有来这里，谁知道你们会做什么……”“谢文东，你听我说，我和周子心不是男朋友和女朋友！”"
    jump node_jf_127

label node_jf_127:
    $ chunky_line("jf-127", "说完，钱大朋生气地走了。")
    narrator "说完，钱大朋生气地走了。"
    jump node_jf_128

label node_jf_128:
    scene bg_campus_day
    show spr_dapeng_angry at left
    show spr_wendong_worried at right
    $ chunky_line("jf-128", "第二天，钱大朋和谢文东还是不说话。")
    narrator "第二天，钱大朋和谢文东还是不说话。"
    jump node_jf_129

label node_jf_129:
    $ chunky_line("jf-129", "吃饭的时候，周子心看到谢文东一个人在吃饭。")
    narrator "吃饭的时候，周子心看到谢文东一个人在吃饭。"
    jump node_jf_130

label node_jf_130:
    $ chunky_line("jf-130", "她问谢文东：“谢文东，昨天你们怎么了？”")
    narrator "她问谢文东：“谢文东，昨天你们怎么了？”"
    jump node_jf_131

label node_jf_131:
    $ chunky_line("jf-131", "“对不起，昨天我有一点......我和钱大朋……有一点生气。”")
    narrator "“对不起，昨天我有一点......我和钱大朋……有一点生气。”"
    jump node_jf_132

label node_jf_132:
    $ chunky_line("jf-132", "谢文东不知道要怎么说，“可是我们是朋友，这没什么。”")
    narrator "谢文东不知道要怎么说，“可是我们是朋友，这没什么。”"
    jump node_jf_133

label node_jf_133:
    $ chunky_line("jf-133", "周子心说：“我知道了。”")
    narrator "周子心说：“我知道了。”"
    jump node_jf_134

label node_jf_134:
    $ chunky_line("jf-134", "“我们不说这个了。”")
    narrator "“我们不说这个了。”"
    jump node_jf_135

label node_jf_135:
    $ chunky_line("jf-135", "谢文东说，“你今天晚上有时间吗？”")
    narrator "谢文东说，“你今天晚上有时间吗？”"
    jump node_jf_136

label node_jf_136:
    $ chunky_line("jf-136", "“我……我今天晚上有时间。”")
    narrator "“我……我今天晚上有时间。”"
    jump node_jf_137

label node_jf_137:
    $ chunky_line("jf-137", "“你知道我们家开饭店，对吧？")
    narrator "“你知道我们家开饭店，对吧？"
    jump node_jf_138

label node_jf_138:
    $ chunky_line("jf-138", "上个月又开了一个饭店。")
    narrator "上个月又开了一个饭店。"
    jump node_jf_139

label node_jf_139:
    $ chunky_line("jf-139", "我爸妈叫我去这个饭店吃饭。”")
    narrator "我爸妈叫我去这个饭店吃饭。”"
    jump node_jf_140

label node_jf_140:
    $ chunky_line("jf-140", "“那你去过了吗？”")
    narrator "“那你去过了吗？”"
    jump node_jf_141

label node_jf_141:
    $ chunky_line("jf-141", "“还没。")
    narrator "“还没。"
    jump node_jf_142

label node_jf_142:
    $ chunky_line("jf-142", "我今天过去。")
    narrator "我今天过去。"
    jump node_jf_143

label node_jf_143:
    $ chunky_line("jf-143", "你也一起来吧。”")
    narrator "你也一起来吧。”"
    jump node_jf_144

label node_jf_144:
    $ chunky_line("jf-144", "谢文东说。")
    narrator "谢文东说。"
    jump node_jf_145

label node_jf_145:
    $ chunky_line("jf-145", "“行，那我再叫几个女生吧。”")
    narrator "“行，那我再叫几个女生吧。”"
    jump node_jf_146

label node_jf_146:
    $ chunky_line("jf-146", "“下次吧。")
    narrator "“下次吧。"
    jump node_jf_147

label node_jf_147:
    $ chunky_line("jf-147", "要是你喜欢我家饭店的菜，再带你的朋友去。”")
    narrator "要是你喜欢我家饭店的菜，再带你的朋友去。”"
    jump node_jf_148

label node_jf_148:
    $ chunky_line("jf-148", "“也行。")
    narrator "“也行。"
    jump node_jf_149

label node_jf_149:
    $ chunky_line("jf-149", "好，那晚上见。”")
    narrator "好，那晚上见。”"
    jump node_jf_150

label node_jf_150:
    $ chunky_line("jf-150", "周子心开心地说。")
    narrator "周子心开心地说。"
    jump node_jf_151

label node_jf_151:
    scene bg_restaurant_night
    show spr_wendong_neutral at left
    show spr_zixin_smile at right
    $ chunky_line("jf-151", "晚上7点，周子心来到了饭店。")
    narrator "晚上7点，周子心来到了饭店。"
    jump node_jf_152

label node_jf_152:
    $ chunky_line("jf-152", "她看到了谢文东。")
    narrator "她看到了谢文东。"
    jump node_jf_153

label node_jf_153:
    $ chunky_line("jf-153", "“周子心，你来了。”")
    narrator "“周子心，你来了。”"
    jump node_jf_154

label node_jf_154:
    $ chunky_line("jf-154", "谢文东马上开心地说。")
    narrator "谢文东马上开心地说。"
    jump node_jf_155

label node_jf_155:
    $ chunky_line("jf-155", "周子心笑了笑说，“文东，你今天为什么不跟我一起来？”")
    narrator "周子心笑了笑说，“文东，你今天为什么不跟我一起来？”"
    jump node_jf_156

label node_jf_156:
    $ chunky_line("jf-156", "“钱大朋看见了会生气的。”")
    narrator "“钱大朋看见了会生气的。”"
    jump node_jf_157

label node_jf_157:
    $ chunky_line("jf-157", "文东小心地说。")
    narrator "文东小心地说。"
    jump node_jf_158

label node_jf_158:
    $ chunky_line("jf-158", "“他为什么要生气？”")
    narrator "“他为什么要生气？”"
    jump node_jf_159

label node_jf_159:
    $ chunky_line("jf-159", "周子心问。")
    narrator "周子心问。"
    jump node_jf_160

label node_jf_160:
    $ chunky_line("jf-160", "“不说他了，我们点菜吧。”")
    narrator "“不说他了，我们点菜吧。”"
    jump node_jf_161

label node_jf_161:
    $ chunky_line("jf-161", "谢文东又笑了，“喜欢吃什么都可以，不要看多少钱。”")
    narrator "谢文东又笑了，“喜欢吃什么都可以，不要看多少钱。”"
    jump node_jf_162

label node_jf_162:
    $ chunky_line("jf-162", "“不行。")
    narrator "“不行。"
    jump node_jf_163

label node_jf_163:
    $ chunky_line("jf-163", "我不能这样做。”")
    narrator "我不能这样做。”"
    jump node_jf_164

label node_jf_164:
    $ chunky_line("jf-164", "周子心也笑了，“我们两个人，点两个菜可以了。”")
    narrator "周子心也笑了，“我们两个人，点两个菜可以了。”"
    jump node_jf_165

label node_jf_165:
    $ chunky_line("jf-165", "“那不行，你是我朋友，我带你来我家饭店吃饭，不能点那么少！")
    narrator "“那不行，你是我朋友，我带你来我家饭店吃饭，不能点那么少！"
    jump node_jf_166

label node_jf_166:
    $ chunky_line("jf-166", "要是你不点，我来点。”")
    narrator "要是你不点，我来点。”"
    jump node_jf_167

label node_jf_167:
    $ chunky_line("jf-167", "说完，谢文东一下子点了五个菜。")
    narrator "说完，谢文东一下子点了五个菜。"
    jump node_jf_168

label node_jf_168:
    $ chunky_line("jf-168", "“你点太多了，我们两个人吃不完的。”")
    narrator "“你点太多了，我们两个人吃不完的。”"
    jump node_jf_169

label node_jf_169:
    $ chunky_line("jf-169", "周子心说。")
    narrator "周子心说。"
    jump node_jf_170

label node_jf_170:
    $ chunky_line("jf-170", "“一点也不多。”")
    narrator "“一点也不多。”"
    jump node_jf_171

label node_jf_171:
    $ chunky_line("jf-171", "谢文东说。")
    narrator "谢文东说。"
    jump node_jf_172

label node_jf_172:
    scene bg_restaurant_night
    show spr_dapeng_angry at left
    show spr_wendong_worried at center
    show spr_zixin_neutral at right
    $ chunky_line("jf-172", "谢文东和周子心还在饭店吃饭的时候，钱大朋也到了饭店。")
    narrator "谢文东和周子心还在饭店吃饭的时候，钱大朋也到了饭店。"
    jump node_jf_173

label node_jf_173:
    $ chunky_line("jf-173", "钱大朋看到了谢文东的爸妈。")
    narrator "钱大朋看到了谢文东的爸妈。"
    jump node_jf_174

label node_jf_174:
    $ chunky_line("jf-174", "“大朋，很长时间没见你了。”")
    narrator "“大朋，很长时间没见你了。”"
    jump node_jf_175

label node_jf_175:
    $ chunky_line("jf-175", "谢爸爸和谢妈妈说，“今天没跟文东一起过来？”")
    narrator "谢爸爸和谢妈妈说，“今天没跟文东一起过来？”"
    jump node_jf_176

label node_jf_176:
    $ chunky_line("jf-176", "“文东没来吗？")
    narrator "“文东没来吗？"
    jump node_jf_177

label node_jf_177:
    $ chunky_line("jf-177", "我听说他今天带女朋友一起过来的。”")
    narrator "我听说他今天带女朋友一起过来的。”"
    jump node_jf_178

label node_jf_178:
    $ chunky_line("jf-178", "钱大朋笑了笑。")
    narrator "钱大朋笑了笑。"
    jump node_jf_179

label node_jf_179:
    $ chunky_line("jf-179", "“文东有女朋友了？”")
    narrator "“文东有女朋友了？”"
    jump node_jf_180

label node_jf_180:
    $ chunky_line("jf-180", "谢爸爸问，“我怎么没听他说过.......”“我也没听他说过。”")
    narrator "谢爸爸问，“我怎么没听他说过.......”“我也没听他说过。”"
    jump node_jf_181

label node_jf_181:
    $ chunky_line("jf-181", "谢妈妈也说。")
    narrator "谢妈妈也说。"
    jump node_jf_182

label node_jf_182:
    $ chunky_line("jf-182", "“我也是听他女朋友的一个朋友说的。”")
    narrator "“我也是听他女朋友的一个朋友说的。”"
    jump node_jf_183

label node_jf_183:
    $ chunky_line("jf-183", "钱大朋说。")
    narrator "钱大朋说。"
    jump node_jf_184

label node_jf_184:
    $ chunky_line("jf-184", "“行，我们知道了。")
    narrator "“行，我们知道了。"
    jump node_jf_185

label node_jf_185:
    $ chunky_line("jf-185", "我问问他。”")
    narrator "我问问他。”"
    jump node_jf_186

label node_jf_186:
    $ chunky_line("jf-186", "谢爸爸说。")
    narrator "谢爸爸说。"
    jump node_jf_187

label node_jf_187:
    $ chunky_line("jf-187", "“文东来了吗？")
    narrator "“文东来了吗？"
    jump node_jf_188

label node_jf_188:
    $ chunky_line("jf-188", "他在哪里？”")
    narrator "他在哪里？”"
    jump node_jf_189

label node_jf_189:
    $ chunky_line("jf-189", "谢妈妈开心地说。")
    narrator "谢妈妈开心地说。"
    jump node_jf_190

label node_jf_190:
    $ chunky_line("jf-190", "“我怎么没看到他......”“在那里，你看！”")
    narrator "“我怎么没看到他......”“在那里，你看！”"
    jump node_jf_191

label node_jf_191:
    $ chunky_line("jf-191", "钱大朋对谢妈妈说，“文东！”")
    narrator "钱大朋对谢妈妈说，“文东！”"
    jump node_jf_192

label node_jf_192:
    $ chunky_line("jf-192", "钱大朋叫。")
    narrator "钱大朋叫。"
    jump node_jf_193

label node_jf_193:
    $ chunky_line("jf-193", "饭店里有很多人在说话，谢文东没听见。")
    narrator "饭店里有很多人在说话，谢文东没听见。"
    jump node_jf_194

label node_jf_194:
    $ chunky_line("jf-194", "“他没听见。")
    narrator "“他没听见。"
    jump node_jf_195

label node_jf_195:
    $ chunky_line("jf-195", "我们还是过去看看吧。”")
    narrator "我们还是过去看看吧。”"
    jump node_jf_196

label node_jf_196:
    $ chunky_line("jf-196", "谢妈妈说。")
    narrator "谢妈妈说。"
    jump node_jf_197

label node_jf_197:
    scene bg_restaurant_night
    show spr_wendong_worried at left
    show spr_zixin_neutral at right
    $ chunky_line("jf-197", "“文东。”")
    narrator "“文东。”"
    jump node_jf_198

label node_jf_198:
    $ chunky_line("jf-198", "谢爸爸叫，“你什么时候来的，也不跟我们说？”")
    narrator "谢爸爸叫，“你什么时候来的，也不跟我们说？”"
    jump node_jf_199

label node_jf_199:
    $ chunky_line("jf-199", "“爸？”")
    narrator "“爸？”"
    jump node_jf_200

label node_jf_200:
    $ chunky_line("jf-200", "谢文东说，“你们今天怎么在店里……”“这是我们的饭店！")
    narrator "谢文东说，“你们今天怎么在店里……”“这是我们的饭店！"
    jump node_jf_201

label node_jf_201:
    $ chunky_line("jf-201", "我们来看看。”")
    narrator "我们来看看。”"
    jump node_jf_202

label node_jf_202:
    $ chunky_line("jf-202", "谢妈妈说。")
    narrator "谢妈妈说。"
    jump node_jf_203

label node_jf_203:
    $ chunky_line("jf-203", "“文东，这是你女朋友吗？”")
    narrator "“文东，这是你女朋友吗？”"
    jump node_jf_204

label node_jf_204:
    $ chunky_line("jf-204", "文东不知道说什么。")
    narrator "文东不知道说什么。"
    jump node_jf_205

label node_jf_205:
    $ chunky_line("jf-205", "“我叫周子心，是文东的朋友。”")
    narrator "“我叫周子心，是文东的朋友。”"
    jump node_jf_206

label node_jf_206:
    $ chunky_line("jf-206", "周子心说，“可是，我不是他女朋友。”")
    narrator "周子心说，“可是，我不是他女朋友。”"
    jump node_jf_207

label node_jf_207:
    $ chunky_line("jf-207", "“文东，你妈问你，你为什么不说话？”")
    narrator "“文东，你妈问你，你为什么不说话？”"
    jump node_jf_208

label node_jf_208:
    $ chunky_line("jf-208", "谢爸爸问。")
    narrator "谢爸爸问。"
    jump node_jf_209

label node_jf_209:
    $ chunky_line("jf-209", "“对……不是女朋友……”文东说。")
    narrator "“对……不是女朋友……”文东说。"
    jump node_jf_210

label node_jf_210:
    $ chunky_line("jf-210", "“文东，那你知不知道她有没有男朋友？”")
    narrator "“文东，那你知不知道她有没有男朋友？”"
    jump node_jf_211

label node_jf_211:
    $ chunky_line("jf-211", "谢妈妈又问。")
    narrator "谢妈妈又问。"
    jump node_jf_212

label node_jf_212:
    $ chunky_line("jf-212", "“妈，你第一次和她见面，问这么多？”")
    narrator "“妈，你第一次和她见面，问这么多？”"
    jump node_jf_213

label node_jf_213:
    $ chunky_line("jf-213", "文东有一点不开心。")
    narrator "文东有一点不开心。"
    jump node_jf_214

label node_jf_214:
    $ chunky_line("jf-214", "“我问一下不行吗？")
    narrator "“我问一下不行吗？"
    jump node_jf_215

label node_jf_215:
    $ chunky_line("jf-215", "我很关心你。”")
    narrator "我很关心你。”"
    jump node_jf_216

label node_jf_216:
    $ chunky_line("jf-216", "谢妈妈没有生气。")
    narrator "谢妈妈没有生气。"
    jump node_jf_217

label node_jf_217:
    $ chunky_line("jf-217", "“你过来也不跟我们说一下。”")
    narrator "“你过来也不跟我们说一下。”"
    jump node_jf_218

label node_jf_218:
    $ chunky_line("jf-218", "谢爸爸听起来有一点不开心，“你能不能多回来看看我们？”")
    narrator "谢爸爸听起来有一点不开心，“你能不能多回来看看我们？”"
    jump node_jf_219

label node_jf_219:
    $ chunky_line("jf-219", "“爸，妈，我知道了……”文东说。")
    narrator "“爸，妈，我知道了……”文东说。"
    jump node_jf_220

label node_jf_220:
    $ chunky_line("jf-220", "“大朋不说，我们都不知道你今天过来了。”")
    narrator "“大朋不说，我们都不知道你今天过来了。”"
    jump node_jf_221

label node_jf_221:
    $ chunky_line("jf-221", "谢爸爸又说。")
    narrator "谢爸爸又说。"
    jump node_jf_222

label node_jf_222:
    $ chunky_line("jf-222", "“大朋？")
    narrator "“大朋？"
    jump node_jf_223

label node_jf_223:
    $ chunky_line("jf-223", "大朋怎么会知道我过来了……”文东看了一下周子心。")
    narrator "大朋怎么会知道我过来了……”文东看了一下周子心。"
    jump node_jf_224

label node_jf_224:
    $ chunky_line("jf-224", "“你在问我吗？”")
    narrator "“你在问我吗？”"
    jump node_jf_225

label node_jf_225:
    $ chunky_line("jf-225", "周子心说，“我一点也不知道，可是我跟我的两个朋友说了晚上要出去吃饭。")
    narrator "周子心说，“我一点也不知道，可是我跟我的两个朋友说了晚上要出去吃饭。"
    jump node_jf_226

label node_jf_226:
    $ chunky_line("jf-226", "可能大朋问过她们……”文东看起来一点也不开心。")
    narrator "可能大朋问过她们……”文东看起来一点也不开心。"
    jump node_jf_227

label node_jf_227:
    $ chunky_line("jf-227", "“大朋还在店里吧？”")
    narrator "“大朋还在店里吧？”"
    jump node_jf_228

label node_jf_228:
    $ chunky_line("jf-228", "他问爸爸。")
    narrator "他问爸爸。"
    jump node_jf_229

label node_jf_229:
    $ chunky_line("jf-229", "“还在，在那里。”")
    narrator "“还在，在那里。”"
    jump node_jf_230

label node_jf_230:
    $ chunky_line("jf-230", "“我有话要跟他说。”")
    narrator "“我有话要跟他说。”"
    jump node_jf_231

label node_jf_231:
    $ chunky_line("jf-231", "说完，谢文东走了过去。")
    narrator "说完，谢文东走了过去。"
    jump node_jf_232

label node_jf_232:
    $ chunky_line("jf-232", "“你们也吃。”")
    narrator "“你们也吃。”"
    jump node_jf_233

label node_jf_233:
    $ chunky_line("jf-233", "周子心对谢爸爸谢妈妈笑了笑。")
    narrator "周子心对谢爸爸谢妈妈笑了笑。"
    jump node_jf_234

label node_jf_234:
    scene bg_family_home
    show spr_wendong_worried at left
    show spr_zixin_smile at right
    $ chunky_line("jf-234", "谢文东走了。")
    narrator "谢文东走了。"
    jump node_jf_235

label node_jf_235:
    $ chunky_line("jf-235", "谢妈妈马上问周子心：“你这么好看，怎么没有男朋友？”")
    narrator "谢妈妈马上问周子心：“你这么好看，怎么没有男朋友？”"
    jump node_jf_236

label node_jf_236:
    $ chunky_line("jf-236", "“我有过男朋友，可是，我们不在一起了。”")
    narrator "“我有过男朋友，可是，我们不在一起了。”"
    jump node_jf_237

label node_jf_237:
    $ chunky_line("jf-237", "周子心说。")
    narrator "周子心说。"
    jump node_jf_238

label node_jf_238:
    $ chunky_line("jf-238", "谢妈妈问：“那你说说，你喜欢什么样的男生？”")
    narrator "谢妈妈问：“那你说说，你喜欢什么样的男生？”"
    jump node_jf_239

label node_jf_239:
    $ chunky_line("jf-239", "周子心笑了一下，不说话。")
    narrator "周子心笑了一下，不说话。"
    jump node_jf_240

label node_jf_240:
    $ chunky_line("jf-240", "谢妈妈看她不说话，又问：“你看我儿子文东怎么样？”")
    narrator "谢妈妈看她不说话，又问：“你看我儿子文东怎么样？”"
    jump node_jf_241

label node_jf_241:
    $ chunky_line("jf-241", "周子心笑了一下，对谢爸爸和谢妈妈说：“文东对他的朋友都很好。")
    narrator "周子心笑了一下，对谢爸爸和谢妈妈说：“文东对他的朋友都很好。"
    jump node_jf_242

label node_jf_242:
    $ chunky_line("jf-242", "可是他不是我喜欢的男生，不是你们想的那样。”")
    narrator "可是他不是我喜欢的男生，不是你们想的那样。”"
    jump node_jf_243

label node_jf_243:
    $ chunky_line("jf-243", "“那钱大朋呢？")
    narrator "“那钱大朋呢？"
    jump node_jf_244

label node_jf_244:
    $ chunky_line("jf-244", "你喜不喜欢钱大朋呢？”")
    narrator "你喜不喜欢钱大朋呢？”"
    jump node_jf_245

label node_jf_245:
    $ chunky_line("jf-245", "谢妈妈笑了笑，又问。")
    narrator "谢妈妈笑了笑，又问。"
    jump node_jf_246

label node_jf_246:
    $ chunky_line("jf-246", "“钱大朋？”")
    narrator "“钱大朋？”"
    jump node_jf_247

label node_jf_247:
    $ chunky_line("jf-247", "周子心问。")
    narrator "周子心问。"
    jump node_jf_248

label node_jf_248:
    $ chunky_line("jf-248", "谢妈妈笑了笑，没说什么。")
    narrator "谢妈妈笑了笑，没说什么。"
    jump node_jf_249

label node_jf_249:
    $ chunky_line("jf-249", "她知道，自己的儿子喜欢这个女生。")
    narrator "她知道，自己的儿子喜欢这个女生。"
    jump node_jf_250

label node_jf_250:
    $ chunky_line("jf-250", "可是钱大朋，她儿子的好朋友，也喜欢这个女生。")
    narrator "可是钱大朋，她儿子的好朋友，也喜欢这个女生。"
    jump node_jf_251

label node_jf_251:
    $ chunky_line("jf-251", "周子心看了一下谢妈妈，说：“钱大朋也是我的朋友。")
    narrator "周子心看了一下谢妈妈，说：“钱大朋也是我的朋友。"
    jump node_jf_252

label node_jf_252:
    $ chunky_line("jf-252", "可是，他也不是我喜欢的男生。”")
    narrator "可是，他也不是我喜欢的男生。”"
    jump node_jf_253

label node_jf_253:
    $ chunky_line("jf-253", "谢妈妈笑了：“那他们知道吗？”")
    narrator "谢妈妈笑了：“那他们知道吗？”"
    jump node_jf_254

label node_jf_254:
    $ chunky_line("jf-254", "“我们没有说过，他们也没问过我。”")
    narrator "“我们没有说过，他们也没问过我。”"
    jump node_jf_255

label node_jf_255:
    $ chunky_line("jf-255", "周子心说得很小心。")
    narrator "周子心说得很小心。"
    jump node_jf_256

label node_jf_256:
    $ chunky_line("jf-256", "谢妈妈笑了笑，没说什么。")
    narrator "谢妈妈笑了笑，没说什么。"
    jump node_jf_257

label node_jf_257:
    scene bg_campus_day
    show spr_dapeng_neutral at left
    show spr_wendong_neutral at right
    $ chunky_line("jf-257", "“钱大朋！”")
    narrator "“钱大朋！”"
    jump node_jf_258

label node_jf_258:
    $ chunky_line("jf-258", "谢文东很生气，“你跟我去外面，我有话要跟你说！”")
    narrator "谢文东很生气，“你跟我去外面，我有话要跟你说！”"
    jump node_jf_259

label node_jf_259:
    $ chunky_line("jf-259", "“你有话要说？")
    narrator "“你有话要说？"
    jump node_jf_260

label node_jf_260:
    $ chunky_line("jf-260", "我也有话要说！”")
    narrator "我也有话要说！”"
    jump node_jf_261

label node_jf_261:
    $ chunky_line("jf-261", "到了外面，钱大朋大叫。")
    narrator "到了外面，钱大朋大叫。"
    jump node_jf_262

label node_jf_262:
    $ chunky_line("jf-262", "“我问你，你跟我爸妈说了什么？”")
    narrator "“我问你，你跟我爸妈说了什么？”"
    jump node_jf_263

label node_jf_263:
    $ chunky_line("jf-263", "“我说了你做的。”")
    narrator "“我说了你做的。”"
    jump node_jf_264

label node_jf_264:
    $ chunky_line("jf-264", "大朋说。")
    narrator "大朋说。"
    jump node_jf_265

label node_jf_265:
    $ chunky_line("jf-265", "“我什么也没做！”")
    narrator "“我什么也没做！”"
    jump node_jf_266

label node_jf_266:
    $ chunky_line("jf-266", "谢文东大叫，“我跟周子心是朋友！")
    narrator "谢文东大叫，“我跟周子心是朋友！"
    jump node_jf_267

label node_jf_267:
    $ chunky_line("jf-267", "朋友！”")
    narrator "朋友！”"
    jump node_jf_268

label node_jf_268:
    $ chunky_line("jf-268", "“那你为什么要带她来饭店吃饭？！”")
    narrator "“那你为什么要带她来饭店吃饭？！”"
    jump node_jf_269

label node_jf_269:
    $ chunky_line("jf-269", "“我和周子心是朋友，你知道吗？")
    narrator "“我和周子心是朋友，你知道吗？"
    jump node_jf_270

label node_jf_270:
    $ chunky_line("jf-270", "我和她一起吃个饭，那又怎么样？”")
    narrator "我和她一起吃个饭，那又怎么样？”"
    jump node_jf_271

label node_jf_271:
    $ chunky_line("jf-271", "文东大叫。")
    narrator "文东大叫。"
    jump node_jf_272

label node_jf_272:
    $ chunky_line("jf-272", "“朋友？")
    narrator "“朋友？"
    jump node_jf_273

label node_jf_273:
    $ chunky_line("jf-273", "今天是朋友，明天是什么？”")
    narrator "今天是朋友，明天是什么？”"
    jump node_jf_274

label node_jf_274:
    $ chunky_line("jf-274", "大朋还是很生气，“女朋友！")
    narrator "大朋还是很生气，“女朋友！"
    jump node_jf_275

label node_jf_275:
    $ chunky_line("jf-275", "我什么都不知道吗？")
    narrator "我什么都不知道吗？"
    jump node_jf_276

label node_jf_276:
    $ chunky_line("jf-276", "我们是朋友吗？！”")
    narrator "我们是朋友吗？！”"
    jump node_jf_277

label node_jf_277:
    $ chunky_line("jf-277", "“你那天还带她去书店和小吃店了！")
    narrator "“你那天还带她去书店和小吃店了！"
    jump node_jf_278

label node_jf_278:
    $ chunky_line("jf-278", "要是我没看到你们，过几天她可能是你女朋友了吧？”")
    narrator "要是我没看到你们，过几天她可能是你女朋友了吧？”"
    jump node_jf_279

label node_jf_279:
    $ chunky_line("jf-279", "谢文东说。")
    narrator "谢文东说。"
    jump node_jf_280

label node_jf_280:
    $ chunky_line("jf-280", "“我们看书，没什么！”")
    narrator "“我们看书，没什么！”"
    jump node_jf_281

label node_jf_281:
    $ chunky_line("jf-281", "钱大朋说。")
    narrator "钱大朋说。"
    jump node_jf_282

label node_jf_282:
    $ chunky_line("jf-282", "“那我们吃饭，也没什么！”")
    narrator "“那我们吃饭，也没什么！”"
    jump node_jf_283

label node_jf_283:
    $ chunky_line("jf-283", "谢文东说。")
    narrator "谢文东说。"
    jump node_jf_284

label node_jf_284:
    $ chunky_line("jf-284", "两个人都很生气，也都不说话了。")
    narrator "两个人都很生气，也都不说话了。"
    jump node_jf_285

label node_jf_285:
    $ chunky_line("jf-285", "过了一会儿，谢文东问大朋：“我们是朋友吗？”")
    narrator "过了一会儿，谢文东问大朋：“我们是朋友吗？”"
    jump node_jf_286

label node_jf_286:
    $ chunky_line("jf-286", "大朋看了看谢文东，说：“文东，我们都喜欢这个女生。")
    narrator "大朋看了看谢文东，说：“文东，我们都喜欢这个女生。"
    jump node_jf_287

label node_jf_287:
    $ chunky_line("jf-287", "可是，我们是那么好的朋友……”大朋不说了。")
    narrator "可是，我们是那么好的朋友……”大朋不说了。"
    jump node_jf_288

label node_jf_288:
    $ chunky_line("jf-288", "“我喜欢她，可是，我做得一点也不对。”")
    narrator "“我喜欢她，可是，我做得一点也不对。”"
    jump node_jf_289

label node_jf_289:
    $ chunky_line("jf-289", "文东看看大朋，说：“我也要你这个朋友。”")
    narrator "文东看看大朋，说：“我也要你这个朋友。”"
    jump node_jf_290

label node_jf_290:
    $ chunky_line("jf-290", "“这也是我要说的。”")
    narrator "“这也是我要说的。”"
    jump node_jf_291

label node_jf_291:
    $ chunky_line("jf-291", "两个人都笑了。")
    narrator "两个人都笑了。"
    jump node_jf_292

label node_jf_292:
    scene bg_family_home
    show spr_dapeng_neutral at left
    show spr_wendong_neutral at right
    $ chunky_line("jf-292", "星期天，谢文东回家吃饭，谢妈妈问：“儿子，你跟大朋还好吧？")
    narrator "星期天，谢文东回家吃饭，谢妈妈问：“儿子，你跟大朋还好吧？"
    jump node_jf_293

label node_jf_293:
    $ chunky_line("jf-293", "那天看你们两个一点也不开心。”")
    narrator "那天看你们两个一点也不开心。”"
    jump node_jf_294

label node_jf_294:
    $ chunky_line("jf-294", "“没什么。")
    narrator "“没什么。"
    jump node_jf_295

label node_jf_295:
    $ chunky_line("jf-295", "都好了。”")
    narrator "都好了。”"
    jump node_jf_296

label node_jf_296:
    $ chunky_line("jf-296", "谢文东笑了一下。")
    narrator "谢文东笑了一下。"
    jump node_jf_297

label node_jf_297:
    $ chunky_line("jf-297", "“对了，那天你和周子心都说什么了？”")
    narrator "“对了，那天你和周子心都说什么了？”"
    jump node_jf_298

label node_jf_298:
    $ chunky_line("jf-298", "“你想听吗？")
    narrator "“你想听吗？"
    jump node_jf_299

label node_jf_299:
    $ chunky_line("jf-299", "那你不要生气。”")
    narrator "那你不要生气。”"
    jump node_jf_300

label node_jf_300:
    $ chunky_line("jf-300", "谢妈妈笑了一下，说：“那天她说，你不是她喜欢的男生。”")
    narrator "谢妈妈笑了一下，说：“那天她说，你不是她喜欢的男生。”"
    jump node_jf_301

label node_jf_301:
    $ chunky_line("jf-301", "谢文东听了，看了看妈妈。")
    narrator "谢文东听了，看了看妈妈。"
    jump node_jf_302

label node_jf_302:
    $ chunky_line("jf-302", "谢妈妈笑了笑说：“儿子，周子心说她也不喜欢大朋。”")
    narrator "谢妈妈笑了笑说：“儿子，周子心说她也不喜欢大朋。”"
    jump node_jf_303

label node_jf_303:
    $ chunky_line("jf-303", "“我不生气。”")
    narrator "“我不生气。”"
    jump node_jf_304

label node_jf_304:
    $ chunky_line("jf-304", "文东笑了笑说，“我昨天看到她跟一个男生走在一起，两个人笑得很开心。”")
    narrator "文东笑了笑说，“我昨天看到她跟一个男生走在一起，两个人笑得很开心。”"
    jump node_jf_305

label node_jf_305:
    $ chunky_line("jf-305", "过了几天，钱大朋对谢文东说：“周子心的男朋友，你知道是谁吗？”")
    narrator "过了几天，钱大朋对谢文东说：“周子心的男朋友，你知道是谁吗？”"
    jump node_jf_306

label node_jf_306:
    $ chunky_line("jf-306", "他们很长时间都没有说过周子心的名字了。")
    narrator "他们很长时间都没有说过周子心的名字了。"
    jump node_jf_307

label node_jf_307:
    $ chunky_line("jf-307", "“他也是我们中山大学的大学生。")
    narrator "“他也是我们中山大学的大学生。"
    jump node_jf_308

label node_jf_308:
    $ chunky_line("jf-308", "老师们都很喜欢他。")
    narrator "老师们都很喜欢他。"
    jump node_jf_309

label node_jf_309:
    $ chunky_line("jf-309", "听说，他下个月要出国了。”")
    narrator "听说，他下个月要出国了。”"
    jump node_jf_310

label node_jf_310:
    $ chunky_line("jf-310", "文东说。")
    narrator "文东说。"
    jump node_jf_311

label node_jf_311:
    $ chunky_line("jf-311", "“不会吧？")
    narrator "“不会吧？"
    jump node_jf_312

label node_jf_312:
    $ chunky_line("jf-312", "那周子心呢？”")
    narrator "那周子心呢？”"
    jump node_jf_313

label node_jf_313:
    $ chunky_line("jf-313", "钱大朋问。")
    narrator "钱大朋问。"
    jump node_jf_314

label node_jf_314:
    $ chunky_line("jf-314", "“不知道，可能也一起去吧。”")
    narrator "“不知道，可能也一起去吧。”"
    jump node_jf_315

label node_jf_315:
    $ chunky_line("jf-315", "谢文东说。")
    narrator "谢文东说。"
    jump node_jf_316

label node_jf_316:
    $ chunky_line("jf-316", "“你……是不是还喜欢她？”")
    narrator "“你……是不是还喜欢她？”"
    jump node_jf_317

label node_jf_317:
    $ chunky_line("jf-317", "谢文东问。")
    narrator "谢文东问。"
    jump node_jf_318

label node_jf_318:
    $ chunky_line("jf-318", "“我不喜欢周子心了，我有喜欢的女生了。")
    narrator "“我不喜欢周子心了，我有喜欢的女生了。"
    jump node_jf_319

label node_jf_319:
    $ chunky_line("jf-319", "你呢？")
    narrator "你呢？"
    jump node_jf_320

label node_jf_320:
    $ chunky_line("jf-320", "你问这个，你是不是还喜欢周子心？”")
    narrator "你问这个，你是不是还喜欢周子心？”"
    jump node_jf_321

label node_jf_321:
    $ chunky_line("jf-321", "钱大朋笑了笑，和文东说。")
    narrator "钱大朋笑了笑，和文东说。"
    jump node_jf_322

label node_jf_322:
    $ chunky_line("jf-322", "“我也有喜欢的女生了。”")
    narrator "“我也有喜欢的女生了。”"
    jump node_jf_323

label node_jf_323:
    $ chunky_line("jf-323", "谢文东也笑了。")
    narrator "谢文东也笑了。"
    jump node_jf_324

label node_jf_324:
    $ chunky_line("jf-324", "谢文东又说：“那个女生做的小吃很好吃，你也吃过。")
    narrator "谢文东又说：“那个女生做的小吃很好吃，你也吃过。"
    jump node_jf_325

label node_jf_325:
    $ chunky_line("jf-325", "她也喜欢……”钱大朋一下子想到了什么：“你说的那个女生是……上次我们和朋友一起吃饭的时候……？”")
    narrator "她也喜欢……”钱大朋一下子想到了什么：“你说的那个女生是……上次我们和朋友一起吃饭的时候……？”"
    jump node_jf_326

label node_jf_326:
    $ chunky_line("jf-326", "“那个朋友的女朋友的朋友？”")
    narrator "“那个朋友的女朋友的朋友？”"
    jump node_jf_327

label node_jf_327:
    $ chunky_line("jf-327", "谢文东不笑了，“你也喜欢？”")
    narrator "谢文东不笑了，“你也喜欢？”"
    jump node_jf_328

label node_jf_328:
    $ chunky_line("jf-328", "钱大朋看了看谢文东，谢文东看了看钱大朋。")
    narrator "钱大朋看了看谢文东，谢文东看了看钱大朋。"
    jump node_jf_329

label node_jf_329:
    $ chunky_line("jf-329", "谢文东说：“大朋，我们是不是好朋友？”")
    narrator "谢文东说：“大朋，我们是不是好朋友？”"
    jump node_jf_result

label node_jf_result:
    narrator "故事读完了。钱大朋和谢文东终于说出了真正想说的话。"
    $ chunky_complete("jf-result", "just-friends-story", "finished")
    return

