# Generated by scripts/renpy/convert-chapters.mjs.
define chunky_chapters = [
    {"id": "ch01-sell-account", "label": "story_ch01_sell_account", "title_zh": "旧账号", "title_en": "The Old Account"},
    {"id": "opening-crossing", "label": "story_opening_crossing", "title_zh": "狭窄房间外的光", "title_en": "Light beyond the narrow room"},
    {"id": "first-lesson", "label": "story_first_lesson", "title_zh": "第一课：先别装高手", "title_en": "First lesson: do not pretend yet"},
    {"id": "ch02-tired-hands", "label": "story_ch02_tired_hands", "title_zh": "被妹妹看见的手", "title_en": "The Hands She Saw"},
    {"id": "ch03-straw-dummy", "label": "story_ch03_straw_dummy", "title_zh": "稻草人", "title_en": "The Straw Dummy"},
    {"id": "ch04-last-student", "label": "story_ch04_last_student", "title_zh": "最后一个人", "title_en": "The Last Student"},
    {"id": "ch05-sculptor-path", "label": "story_ch05_sculptor_path", "title_zh": "雕刻师的路", "title_en": "The Sculptor's Path"},
]
