# Generated by scripts/renpy/convert-chapters.mjs.

define char_lee_hyun = Character("李贤")
define char_lee_hyun_sister = Character("妹妹")
define char_nainai = Character("奶奶")
define char_geomchi = Character("Geomchi")
define char_old_man = Character("老人")
