# Automatic ruby pinyin for all dialogue and menu choices.
#
# How it works:
#   - config.say_menu_text_filter runs on the raw text of every say statement
#     and menu choice BEFORE Ren'Py parses tags/interpolation.
#   - We walk the text, copy {tags} and [interpolation] through untouched, and
#     for each run of Chinese characters we wrap each Han character with ruby
#     tags ({rb}字{/rb}{rt}zì{/rt}) so the pinyin renders above it.
#   - Tone-marked pinyin comes from game/pinyin_map.json, which is generated by
#     `npm run renpy:pinyin` using pinyin-pro (context-aware, so 多音字 are
#     correct). Per-line arrays are tried first; a single-char fallback covers
#     any line that has not been rebuilt yet.
#   - persistent.show_pinyin toggles the whole thing live.

init python:
    import json

    try:
        with renpy.open_file("pinyin_map.json") as _pinyin_file:
            chunky_pinyin = json.loads(_pinyin_file.read().decode("utf-8"))
    except Exception as e:
        chunky_pinyin = {"lines": {}, "chars": {}}

    if "lines" not in chunky_pinyin:
        chunky_pinyin["lines"] = {}
    if "chars" not in chunky_pinyin:
        chunky_pinyin["chars"] = {}

    # CJK punctuation that belongs to a Chinese run but never gets a ruby gloss.
    # Keep this set identical to scripts/renpy/build-pinyin-map.mjs.
    CHUNKY_CJK_PUNCT = set(u"。，、；：？！…—·～〜（）《》〈〉「」『』“”‘’")

    def _chunky_is_han(ch):
        o = ord(ch)
        return (0x3400 <= o <= 0x9FFF) or (0xF900 <= o <= 0xFAFF)

    def _chunky_is_cjk(ch):
        return _chunky_is_han(ch) or ch in CHUNKY_CJK_PUNCT

    def _chunky_rubify_run(run):
        arr = chunky_pinyin["lines"].get(run)
        out = []
        for i, ch in enumerate(run):
            py = None
            if arr is not None and i < len(arr):
                py = arr[i]
            if not py:
                py = chunky_pinyin["chars"].get(ch)
            if _chunky_is_han(ch) and py and py != ch:
                out.append(u"{rb}" + ch + u"{/rb}{rt}" + py + u"{/rt}")
            else:
                out.append(ch)
        return u"".join(out)

    def chunky_pinyin_filter(s):
        if not getattr(store.persistent, "show_pinyin", True):
            return s
        result = []
        i = 0
        n = len(s)
        while i < n:
            ch = s[i]
            if ch == u"{":
                j = s.find(u"}", i)
                if j == -1:
                    result.append(s[i:])
                    break
                result.append(s[i:j + 1])
                i = j + 1
                continue
            if ch == u"[":
                j = s.find(u"]", i)
                if j == -1:
                    result.append(s[i:])
                    break
                result.append(s[i:j + 1])
                i = j + 1
                continue
            if _chunky_is_cjk(ch):
                start = i
                while i < n and _chunky_is_cjk(s[i]):
                    i += 1
                result.append(_chunky_rubify_run(s[start:i]))
                continue
            result.append(ch)
            i += 1
        return u"".join(result)

    config.say_menu_text_filter = chunky_pinyin_filter

    # Default both reading aids on the first time the game runs.
    if persistent.show_pinyin is None:
        persistent.show_pinyin = True
    if persistent.show_english is None:
        persistent.show_english = True

    # Style the ruby (pinyin) text that sits above each character.
    style.default.ruby_style = Style(style.default)
    style.default.ruby_style.size = 22
    style.default.ruby_style.yoffset = -28

# Give dialogue lines extra headroom so the pinyin above the first line is not
# clipped by the top of the text box.
style say_dialogue:
    line_leading 24
