# Entry point. The real content lives in game/story/*.rpy (one label per
# chapter, generated by `npm run renpy:convert` then hand-edited) and the
# reusable framework in game/chunky/*.rpy.

label start:
    $ chunky_event("ready", {})
    show screen chunky_toggles
    jump chunky_menu
